### ISSUE TITLE
`parse` function should be marked `[unsafe]`

### ISSUE THREAD

**Issue by ntrel** [vlang/markdown#5]
Reading past the first element of `text` is `unsafe`.
```v
pub fn C.md_parse(text charptr, size u32, parser &C.MD_PARSER, userdata voidptr) int
pub fn parse(text charptr, size u32, parser &C.MD_PARSER, userdata voidptr) int
```
C.md_parse is also unsafe - why is it `pub`?

Also, IMO it would be better to have a safe interface if V and take a `[]byte`. ~~We should have a way of making a temporary `[]byte` (without allocating) from a pointer and length - it would need `unsafe`~~.

Update: the caller can use `voidptr.vbytes(len)`.

**Comment by spytheman** [comment]
1) `C.md_parse` is no longer `pub`
2) afaik, there are no more unsafe interfaces exposed
